* Encoding: UTF-8.


*Nonparametric Tests: One Sample. 
NPTESTS 
  /ONESAMPLE TEST (e01 e04 e05 e06 e07) KOLMOGOROV_SMIRNOV(NORMAL=SAMPLE ) 
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05 CILEVEL=95.
